-- Part 1: generated by `prisma migrate diff --from-schema <previous schema.prisma> --to-schema prisma/schema.prisma --script`.
-- AlterTable
ALTER TABLE "users" ADD COLUMN     "failed_login_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "locked_until" TIMESTAMPTZ(3);

-- CreateTable
CREATE TABLE "refresh_token_families" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "revoked_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "refresh_token_families_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "family_id" UUID NOT NULL,
    "token_hash" CHAR(64) NOT NULL,
    "revoked_at" TIMESTAMPTZ(3),
    "rotated_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "refresh_token_families_user_id_idx" ON "refresh_token_families"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_token_hash_key" ON "refresh_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "refresh_tokens_family_id_idx" ON "refresh_tokens"("family_id");

-- AddForeignKey
ALTER TABLE "refresh_token_families" ADD CONSTRAINT "refresh_token_families_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "refresh_token_families"("id") ON DELETE CASCADE ON UPDATE CASCADE;



-- Part 2: hand-written. CHECK constraints the Prisma schema cannot express.

ALTER TABLE users
  ADD CONSTRAINT users_failed_login_count_non_negative CHECK (failed_login_count >= 0);

-- Lowercase hex SHA-256 only: a raw token stored here by mistake would be refused.
ALTER TABLE refresh_tokens
  ADD CONSTRAINT refresh_tokens_token_hash_sha256_hex CHECK (token_hash ~ '^[0-9a-f]{64}$');

ALTER TABLE refresh_token_families
  ADD CONSTRAINT refresh_token_families_expires_after_created CHECK (expires_at > created_at);

-- rotated_at is only ever set together with revoked_at, by rotation.
ALTER TABLE refresh_tokens
  ADD CONSTRAINT refresh_tokens_rotated_implies_revoked CHECK (rotated_at IS NULL OR revoked_at IS NOT NULL);
