-- Part 1: generated by `prisma migrate diff --from-schema <previous schema.prisma> --to-schema prisma/schema.prisma --script`.
-- CreateTable
CREATE TABLE "schedule_blocks" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "weekdays" SMALLINT[],
    "start_time" TIME(0) NOT NULL,
    "end_time" TIME(0) NOT NULL,
    "starts_on" DATE NOT NULL,
    "ends_on" DATE,
    "reason" VARCHAR(200),
    "created_by" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "schedule_blocks_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "schedule_blocks_starts_on_idx" ON "schedule_blocks"("starts_on");

-- AddForeignKey
ALTER TABLE "schedule_blocks" ADD CONSTRAINT "schedule_blocks_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;





-- Part 2: hand-written. CHECK constraints the Prisma schema cannot express.

-- Prisma creates list columns as nullable. A block needs 1-7 weekdays, each 0 (Sunday) to 6, and
-- no NULL element. Duplicates are refused by the API: a CHECK cannot count distinct elements.
ALTER TABLE schedule_blocks
  ADD CONSTRAINT schedule_blocks_weekdays_valid CHECK (
    weekdays IS NOT NULL
    AND array_ndims(weekdays) = 1
    AND cardinality(weekdays) BETWEEN 1 AND 7
    AND array_position(weekdays, NULL) IS NULL
    AND weekdays <@ ARRAY[0, 1, 2, 3, 4, 5, 6]::smallint[]
  );

-- Same 'HH:mm' model as availability_rules: whole minutes, 23:59 at most, and a non-empty period.
ALTER TABLE schedule_blocks
  ADD CONSTRAINT schedule_blocks_time_range CHECK (
    start_time < end_time
    AND end_time <= TIME '23:59'
    AND extract(second FROM start_time) = 0
    AND extract(second FROM end_time) = 0
  );

-- ends_on NULL means the block repeats with no end; otherwise the range is inclusive.
ALTER TABLE schedule_blocks
  ADD CONSTRAINT schedule_blocks_date_range CHECK (ends_on IS NULL OR ends_on >= starts_on);

-- The API trims the reason and stores a blank one as NULL.
ALTER TABLE schedule_blocks
  ADD CONSTRAINT schedule_blocks_reason_trimmed CHECK (
    reason IS NULL OR (reason <> '' AND reason = btrim(reason))
  );
