-- Part 1: generated by `prisma migrate diff --from-empty --to-schema prisma/schema.prisma --script`.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('CLIENT', 'ADMIN');

-- CreateEnum
CREATE TYPE "AppointmentStatus" AS ENUM ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'COMPLETED');

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" VARCHAR(100) NOT NULL,
    "email" VARCHAR(254) NOT NULL,
    "password_hash" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'CLIENT',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "starts_at" TIMESTAMPTZ(3) NOT NULL,
    "ends_at" TIMESTAMPTZ(3) NOT NULL,
    "status" "AppointmentStatus" NOT NULL DEFAULT 'PENDING',
    "notes" VARCHAR(500),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "appointments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "availability_rules" (
    "weekday" SMALLINT NOT NULL,
    "opens_at" TIME(0) NOT NULL,
    "closes_at" TIME(0) NOT NULL,
    "slot_minutes" INTEGER NOT NULL,

    CONSTRAINT "availability_rules_pkey" PRIMARY KEY ("weekday")
);

-- CreateTable
CREATE TABLE "closed_dates" (
    "date" DATE NOT NULL,
    "reason" VARCHAR(200) NOT NULL,

    CONSTRAINT "closed_dates_pkey" PRIMARY KEY ("date")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE INDEX "appointments_user_id_starts_at_idx" ON "appointments"("user_id", "starts_at");

-- CreateIndex
CREATE INDEX "appointments_status_starts_at_idx" ON "appointments"("status", "starts_at");

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- Part 2: hand-written. PostgreSQL features the Prisma schema cannot express.
-- Prisma ignores CHECK and EXCLUDE constraints when diffing, so it never tries
-- to drop them. Regenerating this file from the schema would lose them, though.

-- Lets gist indexes mix scalar equality (e.g. a future resource_id WITH =) with
-- range overlap; the tstzrange-only constraint below works without it.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- The application lowercases emails; this makes the database refuse any row
-- that skipped it, so the unique index is case-insensitive in practice.
ALTER TABLE users
  ADD CONSTRAINT users_email_lowercase CHECK (email = lower(email));

ALTER TABLE appointments
  ADD CONSTRAINT appointments_ends_after_starts CHECK (ends_at > starts_at);

-- Guarantees no double booking even under concurrent inserts. tstzrange uses
-- '[)' bounds, so back-to-back slots (09:00-09:30, 09:30-10:00) are allowed.
-- Cancelled and rejected appointments free their slot.
ALTER TABLE appointments ADD CONSTRAINT no_overlap EXCLUDE USING gist (tstzrange(starts_at, ends_at) WITH &&) WHERE (status NOT IN ('CANCELLED', 'REJECTED'));

-- 0 = Sunday ... 6 = Saturday (JavaScript Date#getDay numbering).
ALTER TABLE availability_rules
  ADD CONSTRAINT availability_rules_weekday_range CHECK (weekday BETWEEN 0 AND 6);

-- Business hours never cross midnight.
ALTER TABLE availability_rules
  ADD CONSTRAINT availability_rules_closes_after_opens CHECK (closes_at > opens_at);

-- 5 minutes up to a full 8-hour block.
ALTER TABLE availability_rules
  ADD CONSTRAINT availability_rules_slot_minutes_range CHECK (slot_minutes BETWEEN 5 AND 480);
