export const ERROR_CODES = [
  'IN_PAST',
  'TOO_SOON',
  'TOO_FAR',
  'CANCEL_DEADLINE_PASSED',
  'INVALID_TRANSITION',
  'ACTOR_NOT_ALLOWED',
  'NOT_STARTED_YET',
  'ALREADY_STARTED',
  'CLOSED_DATE',
  'OUTSIDE_BUSINESS_HOURS',
  'MISALIGNED',
  'SLOT_TAKEN',
  'VALIDATION_FAILED',
  'UNAUTHENTICATED',
  'FORBIDDEN',
  'NOT_FOUND',
  'PAYLOAD_TOO_LARGE',
  'RATE_LIMITED',
  'INTERNAL',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
