-- Part 1: generated by `prisma migrate diff --from-schema <previous schema.prisma> --to-schema prisma/schema.prisma --script`.
-- CreateTable
CREATE TABLE "idempotency_keys" (
    "user_id" UUID NOT NULL,
    "key" UUID NOT NULL,
    "request_hash" CHAR(64) NOT NULL,
    "response_status" SMALLINT NOT NULL,
    "response_body" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("user_id","key")
);

-- CreateTable
CREATE TABLE "audit_events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "occurred_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "actor_id" UUID NOT NULL,
    "actor_role" "Role" NOT NULL,
    "action" VARCHAR(64) NOT NULL,
    "entity_type" VARCHAR(64) NOT NULL,
    "entity_id" UUID NOT NULL,
    "from_status" VARCHAR(32),
    "to_status" VARCHAR(32),
    "request_id" VARCHAR(64) NOT NULL,
    "metadata" JSONB,

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "idempotency_keys_created_at_idx" ON "idempotency_keys"("created_at");

-- CreateIndex
CREATE INDEX "audit_events_entity_type_entity_id_occurred_at_idx" ON "audit_events"("entity_type", "entity_id", "occurred_at");

-- CreateIndex
CREATE INDEX "audit_events_actor_id_idx" ON "audit_events"("actor_id");

-- AddForeignKey
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;




-- Part 2: hand-written. CHECK constraints and a trigger the Prisma schema cannot express.

-- The domain models business hours as 'HH:mm' between 00:00 and 23:59, so PostgreSQL's '24:00'
-- and times with seconds are refused here instead of being misread as another time.
ALTER TABLE availability_rules
  ADD CONSTRAINT availability_rules_whole_minutes_until_2359 CHECK (
    closes_at <= TIME '23:59'
    AND extract(second FROM opens_at) = 0
    AND extract(second FROM closes_at) = 0
  );

-- Lowercase hex SHA-256 only.
ALTER TABLE idempotency_keys
  ADD CONSTRAINT idempotency_keys_request_hash_sha256_hex CHECK (request_hash ~ '^[0-9a-f]{64}$');

ALTER TABLE idempotency_keys
  ADD CONSTRAINT idempotency_keys_response_status_range CHECK (response_status BETWEEN 100 AND 599);

ALTER TABLE audit_events
  ADD CONSTRAINT audit_events_action_format CHECK (action ~ '^[A-Z][A-Z_]*$');

-- Append-only: history is never rewritten, even by a bug or a manual fix. The API connects with
-- the same role that owns the tables, so REVOKE UPDATE, DELETE would not bind it; the trigger
-- does. A table owner can still drop the trigger: this guards against mistakes, not a hostile DBA.
CREATE FUNCTION audit_events_reject_change() RETURNS trigger
  LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_events is append-only: % is not allowed', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END;
$$;

CREATE TRIGGER audit_events_no_update_delete
  BEFORE UPDATE OR DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION audit_events_reject_change();

CREATE TRIGGER audit_events_no_truncate
  BEFORE TRUNCATE ON audit_events
  FOR EACH STATEMENT EXECUTE FUNCTION audit_events_reject_change();
